AICoE/meteor

docs/personas.md

Adding a markdown document to list all the personas identified in https://github.com/AICoE/data-driven-development/issues/22 for project meteor

Add personas markdown doc

---

docs/metrics.md

Adding an initial metrics markdown to document all the metrics we would like to collect.
Reference: https://docs.google.com/document/d/1SWv29LkjKUA4rkM3V6bR6GzVWJPWMgHm-RUPH7xiPrE/edit?usp=sharing
Related issue: https://github.com/AICoE/data-driven-development/issues/21
_Note_: This document is likely to be iterated upon and updated over time and this first version is for us to have a good starting point.

Add metrics doc

---

README.md

Meteor community can now follow along on YouTube! :) Adding links to the README for more discoverability.

Add YouTube links

---

src/pages/index.jsx

The tiniest of nits, but saw the button on Meteor webpage is misspelled :sweat_smile: I believe this is the only place it needs to be changed.

typo in button

---

.github/dependabot.yml

SSIA, enable dependency checks for NPM ecosystem.

feat: Add dependabot config

---

OWNERS

SSIA + reorder the list and remove duplicities

feat: Add hema to approvers

---

src/pages/index.jsx

Check out the words, and let me know what you think of the project description + how it works prose.

update front page prose

---

src/pages/index.jsx

Updating the looks of the index page using @isabelizimm's text.
Unstructured layout
/cc @oindrillac @isabelizimm 
@isabelizimm was this the format you imagined for your text?

Index text visual

---

package.json
src/components/Description.jsx
src/components/Meteors.jsx
src/components/MeteorsTitle.jsx
src/pages/index.jsx
src/pages/order/[uid].jsx
src/swr.ts

Qucik refactoring for easier SWR hooks reuse.

refactor: Move SWR hooks into a separate lib

---

next-env.d.ts
src/components/Description.jsx
src/components/Meteors.jsx
src/pages/index.jsx
src/pages/order/[uid].jsx
src/swr.ts

Show outputs from Meteor Status and prefetch api requests.

feat: Prefetch api and show pipeline outputs

---

package-lock.json
package.json

Supersedes https://github.com/AICoE/meteor/pull/118
We have no need for a log viewer anymore.
+ we needed to satisfy some peerDeps

chore: Cleanup dependencies

---

src/pages/order/[uid].jsx

fix: When there's no pipeline to render default to empty array

---

next.config.js

SSIA, resolves regression after #121

fix: Remove log viewer from transpile after deps removal

---

src/components/Form.jsx

feat: Sanitize .git from repo urls

---

manifests/kustomization.yaml
manifests/service.yaml
manifests/servicemonitor.yaml
src/metrics.ts

feat: Prefix and scrape metrics

---

next.config.js

fix: Metrics prefix

---

package.json
src/components/Alerts.jsx
src/components/BranchDropdown.jsx
src/components/Description.jsx
src/components/Dropdown.jsx
src/components/Form.jsx
src/components/Form.module.css
src/components/Layout.jsx
src/components/Meteors.jsx
src/components/Select.jsx
src/components/Select.module.scss
src/constants.ts
src/contexts/Alerts.jsx
src/hooks/swr.ts
src/hooks/useDebounce.ts
src/pages/api/meteors.ts
src/pages/index.jsx
src/pages/order/[uid].jsx
src/styles.css

Part of: https://github.com/AICoE/meteor-operator/issues/42
Implements the TTL dropdown along with better pipeline selector.

feat: Rewamp submit form UI

---

src/components/Meteors.jsx

fix: Pipeline label in dropdown

---

README.md

Part of: https://github.com/AICoE/meteor/issues/186

docs: Update readme with installation guide, replacing '3 teams' sections

---

src/components/Meteors.jsx
src/pages/order/[uid].jsx

fix: Launch button on detail page and make it clickable on list

---

src/components/Form.jsx

fix: TTL submit value

---

.github/bug_report.md
.github/feature_request.md

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

Add GitHub templates for bug and feature

---

src/components/Description.jsx
src/components/Form.jsx
src/pages/order/[uid].jsx

feat: Show persistent meteors expiration as Never

---

docs/adr/000-refactor-pipelines.md

Here is a proposal how to solve https://github.com/AICoE/meteor/issues/90 and https://github.com/AICoE/aicoe-ci/issues/127
Signed-off-by: Christoph Görn <goern@redhat.com>

ADR seperating meteor builder and pipelines

---

.pre-commit-config.yaml

chore: Fix precomit s/git/https/
